[build]
dockerfilePath = "apps/backend/Dockerfile"

[deploy]
startCommand = "echo '--- migrate ---' && npx prisma migrate deploy && echo '--- starting node ---' && ls main.js && node main.js"
restartPolicyType = "ON_FAILURE"
